package Lesson4.HomeWork;

//Declare enum HTTPError
public enum HTTPError {	
	BAD_REQUEST, UNAUTHORIZED, PAYMENT_REQUIRED , FORBIDDEN, NOT_FOUND, METHOD_NOT_ALLOWED, NOT_ACCEPTABLE,
	PROXY_AUTENTIFICATION_REQUIRED, REQUEST_TIMEOUT, CONFLICT, GONE;
}

